<?php

return [
    'permissions' => [
        'websocket_*' => 'Erlaubt Zugriff auf die Websockets des Servers.',
        'control_console' => 'Erlaubt dem Nutzer, Daten an die Serverkonsole zu senden.',
        'control_start' => 'Erlaubt dem Nutzer, die Serverinstanz zu starten.',
        'control_stop' => 'Erlaubt dem Nutzer, die Serverinstanz zu stoppen.',
        'control_restart' => 'Erlaubt dem Nutzer, die Serverinstanz neu zu starten.',
        'control_kill' => 'Erlaubt dem Nutzer, die Serverinstanz zu "töten".',
        'user_create' => 'Erlaubt dem Nutzer, neue Nutzer zur Serverinstanz hinzuzufügen.',
        'user_read' => 'Erlaubt dem Nutzer, die mit diesem Server verbundenen Nutzer anzuzeigen.',
        'user_update' => 'Erlaubt dem Nutzer, andere Nutzer dieser Serverinstanz zu bearbeiten.',
        'user_delete' => 'Erlaubt dem Nutzer, andere Nutzer dieser Serverinstanz zu löschen.',
        'file_create' => 'Erlaubt dem Nutzer, neue Dateien und Verzeichnisse zu erstellen.',
        'file_read' => 'Erlaubt dem Nutzer, Dateien und Ordner dieser Serverinstanz anzuzeigen sowie deren Inhalte einzusehen.',
        'file_update' => 'Erlaubt dem Nutzer, Dateien und Ordner dieser Serverinstanz zu bearbeiten.',
        'file_delete' => 'Erlaubt dem Nutzer, Dateien und Verzeichnisse zu löschen.',
        'file_archive' => 'Erlaubt dem Nutzer, Archivdateien zu erstellen und bestehende Archive zu entpacken.',
        'file_sftp' => 'Erlaubt dem Nutzer, die obigen Dateioperationen über einen SFTP-Client durchzuführen.',
        'allocation_read' => 'Erlaubt dem Nutzer, die Seiten zur Verwaltung von Server-Allokationen aufzurufen.',
        'allocation_update' => 'Erlaubt dem Nutzer, Änderungen an den Allokationen des Servers vorzunehmen.',
        'database_create' => 'Erlaubt dem Nutzer, eine neue Datenbank für den Server zu erstellen.',
        'database_read' => 'Erlaubt dem Nutzer, die Datenbanken des Servers anzuzeigen.',
        'database_update' => 'Erlaubt dem Nutzer, Änderungen an einer Datenbank vorzunehmen. Ohne die Berechtigung "Passwort anzeigen" können Passwörter nicht geändert werden.',
        'database_delete' => 'Erlaubt dem Nutzer, Datenbanken zu löschen.',
        'database_view_password' => 'Erlaubt dem Nutzer, das Passwort einer Datenbank im System anzuzeigen.',
        'schedule_create' => 'Erlaubt dem Nutzer, einen neuen Zeitplan für den Server zu erstellen.',
        'schedule_read' => 'Erlaubt dem Nutzer, Zeitpläne eines Servers anzuzeigen.',
        'schedule_update' => 'Erlaubt dem Nutzer, bestehende Zeitpläne eines Servers zu bearbeiten.',
        'schedule_delete' => 'Erlaubt dem Nutzer, einen Zeitplan für den Server zu löschen.',
    ],
];
